[tool.poetry]
name = "diffusion-python-bot"
version = "0.1.0"
description = "A simple python discord bot for generating images via Stable Diffusion on a local pipeline. In active development, use at your own risk."
authors = ["Merkle <Merkle@>"]
packages = [{include = "diffusion_python_bot"}]

[tool.poetry.scripts]
bot = "diffusion_python_bot.main:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tensorflow-io-gcs-filesystem = "0.31.0"
absl-py = "1.4.0"
accelerate = "0.18.0"
