[tool.poetry]
name = "diffusion-python-bot"
version = "0.1.0"
description = "A simple python discord bot for generating images via Stable Diffusion on a local pipeline. In active development, use at your own risk."
authors = ["Merkle <Merkle@>"]
packages = [{include = "diffusion_python_bot"}]

[tool.poetry.scripts]
bot = "diffusion_python_bot.main:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tensorflow-io-gcs-filesystem = "0.31.0"
absl-py = "1.4.0"
accelerate = "0.18.0"
astunparse = "1.6.3"
cachetools = "5.3.0"
certifi = "2022.12.7"
charset-normalizer = "3.1.0"
diffusers = "0.14.0"
filelock = "3.10.5"
flatbuffers = "23.3.3"
gast = "0.4.0"
google-auth = "2.16.3"
google-auth-oauthlib = "0.4.6"
google-pasta = "0.2.0"
